{{- if .Values.b1admin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-b1admin
  labels:
    app: {{ .Release.Name }}-b1admin
spec:
  replicas: {{ .Values.b1admin.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-b1admin
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-b1admin
    spec:
      containers:
        - name: b1admin
          image: "{{ .Values.b1admin.image.repository }}:{{ .Values.b1admin.image.tag }}"
          imagePullPolicy: {{ .Values.b1admin.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.b1admin.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-b1admin-config
            {{- if .Values.b1admin.secrets }}
            - secretRef:
                name: {{ .Release.Name }}-b1admin-secrets
            {{- end }}
          resources:
            {{- toYaml .Values.b1admin.resources | nindent 12 }}
{{- end }}
