{{- if and .Values.b1admin.enabled .Values.b1admin.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-b1admin
  labels:
    app: {{ .Release.Name }}-b1admin
  annotations:
    {{- toYaml .Values.b1admin.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.b1admin.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.b1admin.ingress.hostname }}
      secretName: {{ .Release.Name }}-b1admin-tls
  {{- end }}
  rules:
    - host: {{ .Values.b1admin.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-b1admin
                port:
                  number: {{ .Values.b1admin.service.port }}
{{- end }}
