{{- if .Values.lessonsapi.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-lessonsapi-config
  labels:
    app: {{ .Release.Name }}-lessonsapi
data:
  {{- range $k, $v := .Values.lessonsapi.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
