{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
    - name: websocket
      port: {{ .Values.api.service.socketPort }}
      targetPort: {{ .Values.api.service.socketPort }}
{{- end }}
