{{- if .Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-api
data:
  {{- range $k, $v := .Values.api.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
