{{- if and .Values.askapi.enabled .Values.askapi.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-askapi-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-askapi
type: Opaque
stringData:
  {{- range $k, $v := .Values.askapi.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
