{{- if (include "b1stack.ingressEnabled" (list . "askapi")) }}
{{- $hostname := include "b1stack.hostname" (list . "askapi" "ask-api") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-askapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-askapi
  annotations:
    {{- include "b1stack.ingressAnnotations" (list . "askapi") | nindent 4 }}
spec:
  ingressClassName: {{ include "b1stack.ingressClassName" (list . "askapi") }}
  {{- if (include "b1stack.ingressTls" (list . "askapi")) }}
  tls:
    - hosts:
        - {{ $hostname }}
      secretName: {{ .Release.Name }}-askapi-tls
  {{- end }}
  rules:
    - host: {{ $hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-askapi
                port:
                  number: {{ .Values.askapi.service.port }}
{{- end }}
