{{- if .Values.askapi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-askapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-askapi
spec:
  type: {{ .Values.askapi.service.type }}
  selector:
    app: {{ .Release.Name }}-askapi
  ports:
    - name: http
      port: {{ .Values.askapi.service.port }}
      targetPort: {{ .Values.askapi.service.port }}
{{- end }}
