{{- if and .Values.askapi.enabled .Values.askapi.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-askapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-askapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-askapi
  minReplicas: {{ .Values.askapi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.askapi.autoscaling.maxReplicas }}
  metrics:
    {{- if gt (int .Values.askapi.autoscaling.targetCPUUtilizationPercentage) 0 }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.askapi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if gt (int .Values.askapi.autoscaling.targetMemoryUtilizationPercentage) 0 }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.askapi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- if .Values.askapi.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.askapi.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}
