{{- if .Values.lessonsapi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-lessonsapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-lessonsapi
spec:
  replicas: {{ .Values.lessonsapi.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-lessonsapi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-lessonsapi
    spec:
      containers:
        - name: lessonsapi
          image: "{{ .Values.lessonsapi.image.repository }}:{{ .Values.lessonsapi.image.tag }}"
          imagePullPolicy: {{ .Values.lessonsapi.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.lessonsapi.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-lessonsapi-config
            {{- if .Values.lessonsapi.secrets }}
            - secretRef:
                name: {{ .Release.Name }}-lessonsapi-secrets
            {{- end }}
          resources:
            {{- toYaml .Values.lessonsapi.resources | nindent 12 }}
{{- end }}
