{{- if and .Values.lessonsapi.enabled .Values.lessonsapi.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-lessonsapi-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-lessonsapi
type: Opaque
stringData:
  {{- range $k, $v := .Values.lessonsapi.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
