{{- if (include "b1stack.ingressEnabled" (list . "lessonsapi")) }}
{{- $hostname := include "b1stack.hostname" (list . "lessonsapi" "lessons-api") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-lessonsapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-lessonsapi
  annotations:
    {{- include "b1stack.ingressAnnotations" (list . "lessonsapi") | nindent 4 }}
spec:
  ingressClassName: {{ include "b1stack.ingressClassName" (list . "lessonsapi") }}
  {{- if (include "b1stack.ingressTls" (list . "lessonsapi")) }}
  tls:
    - hosts:
        - {{ $hostname }}
      secretName: {{ .Release.Name }}-lessonsapi-tls
  {{- end }}
  rules:
    - host: {{ $hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-lessonsapi
                port:
                  number: {{ .Values.lessonsapi.service.port }}
{{- end }}
