{{- if and .Values.lessonsapi.enabled (not .Values.lessonsapi.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-lessonsapi-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-lessonsapi
type: Opaque
stringData:
  ENCRYPTION_KEY: {{ .Values.lessonsapi.secrets.ENCRYPTION_KEY | default (include "b1stack.autoSecret" (list . (printf "%s-lessonsapi-secrets" .Release.Name) "ENCRYPTION_KEY" 24)) | quote }}
  JWT_SECRET: {{ .Values.lessonsapi.secrets.JWT_SECRET | default (include "b1stack.autoSecret" (list . (printf "%s-lessonsapi-secrets" .Release.Name) "JWT_SECRET" 32)) | quote }}
  CONNECTION_STRING: {{ .Values.lessonsapi.secrets.CONNECTION_STRING | default (include "b1stack.connStr" (list "lessons" . "")) | quote }}
  {{- range $k, $v := .Values.lessonsapi.secrets }}
  {{- if and $v (not (has $k (list "ENCRYPTION_KEY" "JWT_SECRET" "CONNECTION_STRING"))) }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
{{- end }}
