{{- if .Values.askapi.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-askapi-config
  labels:
    app: {{ .Release.Name }}-askapi
data:
  {{- range $k, $v := .Values.askapi.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
